language: c
sudo: required
dist: trusty

services:
  - docker

env:
  - OS=ubuntu-x86_64

install:
  - ./contrib/ci/generate_docker.py

script:
  - docker run --privileged -e CI=true -t -v `pwd`/dist:/build/dist fwupd-$OS
